In [1]:
from xgboost import XGBClassifier
import numpy as np

/usr/local/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
X, y = np.random.rand(10000, 5), np.random.randint(2, size=10000)

In [3]:
classifier = XGBClassifier(max_depth=3, n_estimators=100)

In [4]:
classifier.fit(X, y)

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='binary:logistic', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

In [5]:
classifier.booster().dump_model('random-data.model')

In [6]:
print(X[:5], y[:5])

[[ 0.35360441  0.61575975  0.96075097  0.14916234  0.02395255]
 [ 0.17025     0.8991542   0.22692291  0.65589836  0.98354182]
 [ 0.21876515  0.31419312  0.68969528  0.45303464  0.6658634 ]
 [ 0.18444766  0.83448066  0.85196587  0.7840865   0.65353192]
 [ 0.78992684  0.13626236  0.57394773  0.82488575  0.9654286 ]] [0 0 0 0 1]


In [7]:
print(classifier.predict_proba(X[:5]))

[[ 0.54862255  0.45137745]
 [ 0.5883804   0.4116196 ]
 [ 0.4924444   0.5075556 ]
 [ 0.54426908  0.45573092]
 [ 0.49874032  0.50125968]]
